### ISSUE TITLE
Attempted to load interface "ChainedRouterInterface" from namespace "Symfony\Cmf\Component\Routing".

### ISSUE THREAD

**Issue by Nabilcnpe** [symfony-cmf/Routing#193]
hey guys, 

I can't see why i got this error ! i put the routing folder in the vendors/symfony
but i don't know why he can't find the chainedRouterInterface 
Please i need your help 

Thanks

**Comment by dbu** [comment]
could you have a version mismatch between symfony-cmf/routing and symfony-cmf/routing-bundle? did you check if vendor/symfony-cmf/routing/src/ChainedRouterInterface.php exists? did you use composer or just "put" the repository somewhere? composer needs to run to update the autoloading information.

**Comment by Nabilcnpe** [comment]
vendor/symfony-cmf/routing/src/ChainedRouterInterface.php yes it exists 
in fact i didn't use composer because i can't due to proxy issues i just put the repository in the vendor/symfony-cmf 
and when i try to run composer.phar update of course it doesn't work as i said due to proxy issues

**Comment by Nabilcnpe** [comment]
how can i tell if i have a mismatch between symfony-cmf/routing and symfony-cmf/routing-bundle ?

Thank you so much for your help

**Comment by dbu** [comment]
if the interface file is present, then you don't have that mismatch. i was afraid you might have version 2 of the bundle and verison 1.x of the component, because this interface is new in version 2.

are you sure that autoloading is working in general? you should make composer work with your proxy or fix the proxy or something, would be much easier if composer could just generate the normal autoload files.

**Comment by Nabilcnpe** [comment]
Okey i will try to fix the proxy thank you !
